### ISSUE TITLE
It should send an SMS immediately when showing verify-token page

### ISSUE THREAD

**Issue by jaredsohn** [authy/authy-devise#55]
I would like it if when the user visits the verify-token page, it would automatically send them an SMS so that the user doesn't have to click a button after entering the page. This seems similar to how gmail handles two factor authentication.

Is there a way to configure devise-authy to work this way or an easy way to add such functionality?  (I imagine you can get something kind of close if you set up authy to send an authy link upon user creation but that assumes that users are allowed to use the authy app and that only happens upon account creation and not when the two factor auth expires.)

**Comment by jaredsohn** [comment]
If there isn't a built-in way (which I think would be a useful feature), it looks like a custom Devise::DeviseAuthyController should accomplish this.

**Comment by tom-lord** [comment]
Hi @jaredsohn, would you be able to elaborate a little on what your solution was? Here's how I solved the same issue:

`./config/initializers/devise_authy_controller_overrides.rb`:

```
module DeviseAuthyControllerOverrides 
  def GET_verify_authy 
    super 
    Authy::API.request_sms(:id => @resource.authy_id, :force => true) 
  end 
 
  def GET_verify_authy_installation 
    super 
    Authy::API.request_sms(:id => @resource.authy_id, :force => true) 
  end 
end 
 
Devise::DeviseAuthyController.prepend(DeviseAuthyControllerOverrides)
```

However, prepending to a class like this can cause issues - mainly in development mode, when switching git branches. I would rather solve this by sub-classing the `Devise::DeviseAuthyController` class like [this](https://gist.github.com/kinopyo/2343176), but for some reason I was unable to re-define the routes in `config/routes.rb`; perhaps because of the unusual way in which they are [defined](https://github.com/authy/authy-devise/blob/master/lib/devise-authy/routes.rb).
