### ISSUE TITLE
Interest in backport to Rails 3?

### ISSUE THREAD

**Issue by j-ro** [authy/authy-devise#80]
Hey folks, like many, we're still on Rails 3 and will be for the foreseeable. We've backported this gem to work with Rails 3, because after the upgrade (https://github.com/authy/authy-devise/pull/52) this gem got a lot of important security patches that we needed too.

We're happy to share this code, and happy to turn it over for official hosting. I'm not exactly sure the best way to do that -- we could put it on our GitHub and you could link, or any other solution really. Let me know if there's interest in this and we can figure out the best way to make it available.

**Comment by LucasVidal** [comment]
Hey @j-ro !

After some discussion, we decided that we won't have the bandwidth to host/maintain the Rails 3 backport. What we can do is to link your repo from the Readme here, so that anyone who has the same necessity can quickly find you. 

Does that sound good to you? 
Feel free to share your repo and we'll link it.

Thanks!

**Comment by j-ro** [comment]
Sounds good! Repo is here, feel free to link it up!

https://github.com/gcosta/authy-devise
